USE db_autogenerated;

-- primera consulta
SELECT postalZip, region, country FROM myTable;

-- segunda consulta
SELECT *
FROM mytable
WHERE SUBSTRING(phone, 1, 5) = '(811)';

-- tercera consulta
SELECT *
FROM mytable
WHERE country = 'Spain' OR country = 'Italy';

-- cuarta consulta
SELECT COUNT(*) AS total_records
FROM mytable;

-- quinta consulta
SELECT 
    region, 
    country, 
    postalZip 
FROM 
    mytable 
WHERE 
    country IN (SELECT country FROM mytable WHERE country IN ('Germany', 'Turkey')) ;
    
-- sexta consulta
SELECT 
    MAX(id),
    MIN(id)
FROM 
    mytable;
    
-- septima consulta   
SELECT country,
COUNT(*) AS total
FROM mytable
GROUP BY country ;

-- octava consulta
SELECT * FROM mytable ORDER BY postalZip
LIMIT 10;

-- novena consulta
SET SQL_SAFE_UPDATES = 0;
DELETE FROM mytable WHERE region='Singapore';
SET SQL_SAFE_UPDATES = 1;
-- desactivamos la actualizacion segura y la volvemos a activar


